### ISSUE TITLE
Broken Link in BMC Part 1

### ISSUE THREAD

**Issue by PlaidDroid** [valvers/valvers.website.src#1]
The link http://www.valvers.com/embedded-linux/raspberry-pi/step02-bare-metal-programming-in-c-pt2 at the end of the page is very broken. I guess it should lead to part 2. 

I'm submitting a PR replacing it with https://www.valvers.com/open-software/raspberry-pi/bare-metal-programming-in-c-part-2 leading to the next part.

**Comment by PlaidDroid** [comment]
Thank you for these tutorials by the way!

**Comment by BrianSidebotham** [comment]
Hi @PlaidDroid 
Thanks for registering the issue. The reason for that link is that URL is a legacy landing point for that page.

The actual issue is in the redirect in `mkdocs.template.yml`. You can see the error in there. Would you mind changing the PR in order to fix it in the template?

The link source actually comes from https://github.com/BrianSidebotham/arm-tutorial-rpi/tree/master/part-1 and yes, the 404 response page on valvers.com is currently very broken!! That'd also be good to fix, but as a separate issue.

**Comment by PlaidDroid** [comment]
I've edited the links. I guess it's good then?

**Comment by BrianSidebotham** [comment]
Yes, all good @PlaidDroid 

Thanks for your contribution! :+1:
